### ISSUE TITLE
Allow zero character passwords

### ISSUE THREAD

**Issue by P0nt14c** [RITRedteam/nosferatu#1]
Improve the usability of Nosferatu by adding the ability to have a zero character password

**Comment by d3adzo** [comment]
The MsvpPasswordValidate hooking in this project is related to having a specific replacement for the first 16 bytes of memory of the SAMPR struct (NTLM hash). Blank passwords are a separate capability with Windows systems.

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-samr/50d17755-c6b8-40bd-8cac-bd6cfa31adf2
